services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    networks:
      - backend

  voting-app:
    build:
      context: ./vote
      dockerfile: Dockerfile
    container_name: "voting-app"
    ports:
      - "5000:80"
    networks:
      - front-end
      - backend
    depends_on:
      - redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: "worker"
    networks:
      - backend
    depends_on:
      - redis
      - db

  db:
    image: "postgres:latest"
    container_name: "db"
    networks:
      - backend
  result-app:
    build:
      context: ./result
      dockerfile: Dockerfile
    container_name: "result-app"
    ports:
      - "5001:80"
    networks:
      - front-end
      - backend
    depends_on:
      - db

networks:
  front-end:
    driver: bridge
  backend:
    driver: bridge
